// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pi/agent/v1/pi_agent.proto

package piagentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PiAgent_GetState_FullMethodName        = "/pi.agent.v1.PiAgent/GetState"
	PiAgent_Prompt_FullMethodName          = "/pi.agent.v1.PiAgent/Prompt"
	PiAgent_Steer_FullMethodName           = "/pi.agent.v1.PiAgent/Steer"
	PiAgent_FollowUp_FullMethodName        = "/pi.agent.v1.PiAgent/FollowUp"
	PiAgent_Abort_FullMethodName           = "/pi.agent.v1.PiAgent/Abort"
	PiAgent_NewSession_FullMethodName      = "/pi.agent.v1.PiAgent/NewSession"
	PiAgent_ListCommands_FullMethodName    = "/pi.agent.v1.PiAgent/ListCommands"
	PiAgent_ExecuteCommand_FullMethodName  = "/pi.agent.v1.PiAgent/ExecuteCommand"
	PiAgent_GetMessages_FullMethodName     = "/pi.agent.v1.PiAgent/GetMessages"
	PiAgent_ReadBlob_FullMethodName        = "/pi.agent.v1.PiAgent/ReadBlob"
	PiAgent_SubscribeEvents_FullMethodName = "/pi.agent.v1.PiAgent/SubscribeEvents"
)

// PiAgentClient is the client API for PiAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PiAgentClient interface {
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*SessionState, error)
	Prompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*CommandAck, error)
	Steer(ctx context.Context, in *SteerRequest, opts ...grpc.CallOption) (*CommandAck, error)
	FollowUp(ctx context.Context, in *FollowUpRequest, opts ...grpc.CallOption) (*CommandAck, error)
	Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*CommandAck, error)
	NewSession(ctx context.Context, in *NewSessionRequest, opts ...grpc.CallOption) (*SessionSwitchResult, error)
	ListCommands(ctx context.Context, in *ListCommandsRequest, opts ...grpc.CallOption) (*ListCommandsResponse, error)
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*CommandAck, error)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	ReadBlob(ctx context.Context, in *ReadBlobRequest, opts ...grpc.CallOption) (*ReadBlobResponse, error)
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventBatch], error)
}

type piAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewPiAgentClient(cc grpc.ClientConnInterface) PiAgentClient {
	return &piAgentClient{cc}
}

func (c *piAgentClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*SessionState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionState)
	err := c.cc.Invoke(ctx, PiAgent_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piAgentClient) Prompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, PiAgent_Prompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piAgentClient) Steer(ctx context.Context, in *SteerRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, PiAgent_Steer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piAgentClient) FollowUp(ctx context.Context, in *FollowUpRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, PiAgent_FollowUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piAgentClient) Abort(ctx context.Context, in *AbortRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, PiAgent_Abort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piAgentClient) NewSession(ctx context.Context, in *NewSessionRequest, opts ...grpc.CallOption) (*SessionSwitchResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionSwitchResult)
	err := c.cc.Invoke(ctx, PiAgent_NewSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piAgentClient) ListCommands(ctx context.Context, in *ListCommandsRequest, opts ...grpc.CallOption) (*ListCommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommandsResponse)
	err := c.cc.Invoke(ctx, PiAgent_ListCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piAgentClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*CommandAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandAck)
	err := c.cc.Invoke(ctx, PiAgent_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piAgentClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, PiAgent_GetMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piAgentClient) ReadBlob(ctx context.Context, in *ReadBlobRequest, opts ...grpc.CallOption) (*ReadBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadBlobResponse)
	err := c.cc.Invoke(ctx, PiAgent_ReadBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *piAgentClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PiAgent_ServiceDesc.Streams[0], PiAgent_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEventsRequest, EventBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PiAgent_SubscribeEventsClient = grpc.ServerStreamingClient[EventBatch]

// PiAgentServer is the server API for PiAgent service.
// All implementations must embed UnimplementedPiAgentServer
// for forward compatibility.
type PiAgentServer interface {
	GetState(context.Context, *GetStateRequest) (*SessionState, error)
	Prompt(context.Context, *PromptRequest) (*CommandAck, error)
	Steer(context.Context, *SteerRequest) (*CommandAck, error)
	FollowUp(context.Context, *FollowUpRequest) (*CommandAck, error)
	Abort(context.Context, *AbortRequest) (*CommandAck, error)
	NewSession(context.Context, *NewSessionRequest) (*SessionSwitchResult, error)
	ListCommands(context.Context, *ListCommandsRequest) (*ListCommandsResponse, error)
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*CommandAck, error)
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
	ReadBlob(context.Context, *ReadBlobRequest) (*ReadBlobResponse, error)
	SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[EventBatch]) error
	mustEmbedUnimplementedPiAgentServer()
}

// UnimplementedPiAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPiAgentServer struct{}

func (UnimplementedPiAgentServer) GetState(context.Context, *GetStateRequest) (*SessionState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedPiAgentServer) Prompt(context.Context, *PromptRequest) (*CommandAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prompt not implemented")
}
func (UnimplementedPiAgentServer) Steer(context.Context, *SteerRequest) (*CommandAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Steer not implemented")
}
func (UnimplementedPiAgentServer) FollowUp(context.Context, *FollowUpRequest) (*CommandAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowUp not implemented")
}
func (UnimplementedPiAgentServer) Abort(context.Context, *AbortRequest) (*CommandAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Abort not implemented")
}
func (UnimplementedPiAgentServer) NewSession(context.Context, *NewSessionRequest) (*SessionSwitchResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewSession not implemented")
}
func (UnimplementedPiAgentServer) ListCommands(context.Context, *ListCommandsRequest) (*ListCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCommands not implemented")
}
func (UnimplementedPiAgentServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*CommandAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedPiAgentServer) GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}
func (UnimplementedPiAgentServer) ReadBlob(context.Context, *ReadBlobRequest) (*ReadBlobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBlob not implemented")
}
func (UnimplementedPiAgentServer) SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[EventBatch]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedPiAgentServer) mustEmbedUnimplementedPiAgentServer() {}
func (UnimplementedPiAgentServer) testEmbeddedByValue()                 {}

// UnsafePiAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PiAgentServer will
// result in compilation errors.
type UnsafePiAgentServer interface {
	mustEmbedUnimplementedPiAgentServer()
}

func RegisterPiAgentServer(s grpc.ServiceRegistrar, srv PiAgentServer) {
	// If the following call pancis, it indicates UnimplementedPiAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PiAgent_ServiceDesc, srv)
}

func _PiAgent_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiAgentServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiAgent_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiAgentServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiAgent_Prompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiAgentServer).Prompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiAgent_Prompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiAgentServer).Prompt(ctx, req.(*PromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiAgent_Steer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SteerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiAgentServer).Steer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiAgent_Steer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiAgentServer).Steer(ctx, req.(*SteerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiAgent_FollowUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiAgentServer).FollowUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiAgent_FollowUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiAgentServer).FollowUp(ctx, req.(*FollowUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiAgent_Abort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiAgentServer).Abort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiAgent_Abort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiAgentServer).Abort(ctx, req.(*AbortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiAgent_NewSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiAgentServer).NewSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiAgent_NewSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiAgentServer).NewSession(ctx, req.(*NewSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiAgent_ListCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiAgentServer).ListCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiAgent_ListCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiAgentServer).ListCommands(ctx, req.(*ListCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiAgent_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiAgentServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiAgent_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiAgentServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiAgent_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiAgentServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiAgent_GetMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiAgentServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiAgent_ReadBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PiAgentServer).ReadBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PiAgent_ReadBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PiAgentServer).ReadBlob(ctx, req.(*ReadBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PiAgent_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PiAgentServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeEventsRequest, EventBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PiAgent_SubscribeEventsServer = grpc.ServerStreamingServer[EventBatch]

// PiAgent_ServiceDesc is the grpc.ServiceDesc for PiAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PiAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pi.agent.v1.PiAgent",
	HandlerType: (*PiAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _PiAgent_GetState_Handler,
		},
		{
			MethodName: "Prompt",
			Handler:    _PiAgent_Prompt_Handler,
		},
		{
			MethodName: "Steer",
			Handler:    _PiAgent_Steer_Handler,
		},
		{
			MethodName: "FollowUp",
			Handler:    _PiAgent_FollowUp_Handler,
		},
		{
			MethodName: "Abort",
			Handler:    _PiAgent_Abort_Handler,
		},
		{
			MethodName: "NewSession",
			Handler:    _PiAgent_NewSession_Handler,
		},
		{
			MethodName: "ListCommands",
			Handler:    _PiAgent_ListCommands_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _PiAgent_ExecuteCommand_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _PiAgent_GetMessages_Handler,
		},
		{
			MethodName: "ReadBlob",
			Handler:    _PiAgent_ReadBlob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _PiAgent_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pi/agent/v1/pi_agent.proto",
}
