// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pi/agent/v1/pi_agent.proto

package piagentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamingBehavior int32

const (
	StreamingBehavior_STREAMING_BEHAVIOR_UNSPECIFIED StreamingBehavior = 0
	StreamingBehavior_STREAMING_BEHAVIOR_STEER       StreamingBehavior = 1
	StreamingBehavior_STREAMING_BEHAVIOR_FOLLOW_UP   StreamingBehavior = 2
)

// Enum value maps for StreamingBehavior.
var (
	StreamingBehavior_name = map[int32]string{
		0: "STREAMING_BEHAVIOR_UNSPECIFIED",
		1: "STREAMING_BEHAVIOR_STEER",
		2: "STREAMING_BEHAVIOR_FOLLOW_UP",
	}
	StreamingBehavior_value = map[string]int32{
		"STREAMING_BEHAVIOR_UNSPECIFIED": 0,
		"STREAMING_BEHAVIOR_STEER":       1,
		"STREAMING_BEHAVIOR_FOLLOW_UP":   2,
	}
)

func (x StreamingBehavior) Enum() *StreamingBehavior {
	p := new(StreamingBehavior)
	*p = x
	return p
}

func (x StreamingBehavior) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamingBehavior) Descriptor() protoreflect.EnumDescriptor {
	return file_pi_agent_v1_pi_agent_proto_enumTypes[0].Descriptor()
}

func (StreamingBehavior) Type() protoreflect.EnumType {
	return &file_pi_agent_v1_pi_agent_proto_enumTypes[0]
}

func (x StreamingBehavior) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamingBehavior.Descriptor instead.
func (StreamingBehavior) EnumDescriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{0}
}

type EventLevel int32

const (
	EventLevel_EVENT_LEVEL_SUMMARY EventLevel = 0
	EventLevel_EVENT_LEVEL_NONE    EventLevel = 1
	EventLevel_EVENT_LEVEL_STATE   EventLevel = 2
	EventLevel_EVENT_LEVEL_FULL    EventLevel = 3
)

// Enum value maps for EventLevel.
var (
	EventLevel_name = map[int32]string{
		0: "EVENT_LEVEL_SUMMARY",
		1: "EVENT_LEVEL_NONE",
		2: "EVENT_LEVEL_STATE",
		3: "EVENT_LEVEL_FULL",
	}
	EventLevel_value = map[string]int32{
		"EVENT_LEVEL_SUMMARY": 0,
		"EVENT_LEVEL_NONE":    1,
		"EVENT_LEVEL_STATE":   2,
		"EVENT_LEVEL_FULL":    3,
	}
)

func (x EventLevel) Enum() *EventLevel {
	p := new(EventLevel)
	*p = x
	return p
}

func (x EventLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_pi_agent_v1_pi_agent_proto_enumTypes[1].Descriptor()
}

func (EventLevel) Type() protoreflect.EnumType {
	return &file_pi_agent_v1_pi_agent_proto_enumTypes[1]
}

func (x EventLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventLevel.Descriptor instead.
func (EventLevel) EnumDescriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{1}
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{0}
}

type GetMessagesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InlinePayloads  bool                   `protobuf:"varint,1,opt,name=inline_payloads,json=inlinePayloads,proto3" json:"inline_payloads,omitempty"`
	InlineByteLimit uint32                 `protobuf:"varint,2,opt,name=inline_byte_limit,json=inlineByteLimit,proto3" json:"inline_byte_limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetMessagesRequest) GetInlinePayloads() bool {
	if x != nil {
		return x.InlinePayloads
	}
	return false
}

func (x *GetMessagesRequest) GetInlineByteLimit() uint32 {
	if x != nil {
		return x.InlineByteLimit
	}
	return 0
}

type ReadBlobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlobId        string                 `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBlobRequest) Reset() {
	*x = ReadBlobRequest{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBlobRequest) ProtoMessage() {}

func (x *ReadBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBlobRequest.ProtoReflect.Descriptor instead.
func (*ReadBlobRequest) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ReadBlobRequest) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *ReadBlobRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadBlobRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReadBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlobId        string                 `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Eof           bool                   `protobuf:"varint,5,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadBlobResponse) Reset() {
	*x = ReadBlobResponse{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadBlobResponse) ProtoMessage() {}

func (x *ReadBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadBlobResponse.ProtoReflect.Descriptor instead.
func (*ReadBlobResponse) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ReadBlobResponse) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *ReadBlobResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadBlobResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadBlobResponse) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *ReadBlobResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type PromptRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Message           string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Images            []*Image               `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	StreamingBehavior StreamingBehavior      `protobuf:"varint,3,opt,name=streaming_behavior,json=streamingBehavior,proto3,enum=pi.agent.v1.StreamingBehavior" json:"streaming_behavior,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PromptRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PromptRequest) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *PromptRequest) GetStreamingBehavior() StreamingBehavior {
	if x != nil {
		return x.StreamingBehavior
	}
	return StreamingBehavior_STREAMING_BEHAVIOR_UNSPECIFIED
}

type SteerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Images        []*Image               `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SteerRequest) Reset() {
	*x = SteerRequest{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SteerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SteerRequest) ProtoMessage() {}

func (x *SteerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SteerRequest.ProtoReflect.Descriptor instead.
func (*SteerRequest) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{5}
}

func (x *SteerRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SteerRequest) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type FollowUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Images        []*Image               `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUpRequest) Reset() {
	*x = FollowUpRequest{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUpRequest) ProtoMessage() {}

func (x *FollowUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUpRequest.ProtoReflect.Descriptor instead.
func (*FollowUpRequest) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{6}
}

func (x *FollowUpRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FollowUpRequest) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{7}
}

type NewSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentSession *string                `protobuf:"bytes,1,opt,name=parent_session,json=parentSession,proto3,oneof" json:"parent_session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewSessionRequest) Reset() {
	*x = NewSessionRequest{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewSessionRequest) ProtoMessage() {}

func (x *NewSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewSessionRequest.ProtoReflect.Descriptor instead.
func (*NewSessionRequest) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{8}
}

func (x *NewSessionRequest) GetParentSession() string {
	if x != nil && x.ParentSession != nil {
		return *x.ParentSession
	}
	return ""
}

type ListCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandsRequest) Reset() {
	*x = ListCommandsRequest{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsRequest) ProtoMessage() {}

func (x *ListCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsRequest.ProtoReflect.Descriptor instead.
func (*ListCommandsRequest) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{9}
}

type ExecuteCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          string                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteCommandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExecuteCommandRequest) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

type ListCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*SlashCommand        `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandsResponse) Reset() {
	*x = ListCommandsResponse{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsResponse) ProtoMessage() {}

func (x *ListCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsResponse.ProtoReflect.Descriptor instead.
func (*ListCommandsResponse) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ListCommandsResponse) GetCommands() []*SlashCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type SlashCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	SourceInfo    *SourceInfo            `protobuf:"bytes,4,opt,name=source_info,json=sourceInfo,proto3" json:"source_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlashCommand) Reset() {
	*x = SlashCommand{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlashCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlashCommand) ProtoMessage() {}

func (x *SlashCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlashCommand.ProtoReflect.Descriptor instead.
func (*SlashCommand) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{12}
}

func (x *SlashCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SlashCommand) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SlashCommand) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SlashCommand) GetSourceInfo() *SourceInfo {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

type SourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Origin        string                 `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	BaseDir       string                 `protobuf:"bytes,5,opt,name=base_dir,json=baseDir,proto3" json:"base_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceInfo) Reset() {
	*x = SourceInfo{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceInfo) ProtoMessage() {}

func (x *SourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceInfo.ProtoReflect.Descriptor instead.
func (*SourceInfo) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{13}
}

func (x *SourceInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SourceInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SourceInfo) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SourceInfo) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *SourceInfo) GetBaseDir() string {
	if x != nil {
		return x.BaseDir
	}
	return ""
}

type SubscribeEventsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Level           EventLevel             `protobuf:"varint,1,opt,name=level,proto3,enum=pi.agent.v1.EventLevel" json:"level,omitempty"`
	BatchWindowMs   uint32                 `protobuf:"varint,2,opt,name=batch_window_ms,json=batchWindowMs,proto3" json:"batch_window_ms,omitempty"`
	MaxBatchSize    uint32                 `protobuf:"varint,3,opt,name=max_batch_size,json=maxBatchSize,proto3" json:"max_batch_size,omitempty"`
	AfterSequence   uint64                 `protobuf:"varint,4,opt,name=after_sequence,json=afterSequence,proto3" json:"after_sequence,omitempty"`
	InlinePayloads  bool                   `protobuf:"varint,5,opt,name=inline_payloads,json=inlinePayloads,proto3" json:"inline_payloads,omitempty"`
	InlineByteLimit uint32                 `protobuf:"varint,6,opt,name=inline_byte_limit,json=inlineByteLimit,proto3" json:"inline_byte_limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscribeEventsRequest) Reset() {
	*x = SubscribeEventsRequest{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEventsRequest) ProtoMessage() {}

func (x *SubscribeEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeEventsRequest) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{14}
}

func (x *SubscribeEventsRequest) GetLevel() EventLevel {
	if x != nil {
		return x.Level
	}
	return EventLevel_EVENT_LEVEL_SUMMARY
}

func (x *SubscribeEventsRequest) GetBatchWindowMs() uint32 {
	if x != nil {
		return x.BatchWindowMs
	}
	return 0
}

func (x *SubscribeEventsRequest) GetMaxBatchSize() uint32 {
	if x != nil {
		return x.MaxBatchSize
	}
	return 0
}

func (x *SubscribeEventsRequest) GetAfterSequence() uint64 {
	if x != nil {
		return x.AfterSequence
	}
	return 0
}

func (x *SubscribeEventsRequest) GetInlinePayloads() bool {
	if x != nil {
		return x.InlinePayloads
	}
	return false
}

func (x *SubscribeEventsRequest) GetInlineByteLimit() uint32 {
	if x != nil {
		return x.InlineByteLimit
	}
	return 0
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{15}
}

func (x *Image) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Image) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type SessionState struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Model                 *Model                 `protobuf:"bytes,1,opt,name=model,proto3,oneof" json:"model,omitempty"`
	ThinkingLevel         string                 `protobuf:"bytes,2,opt,name=thinking_level,json=thinkingLevel,proto3" json:"thinking_level,omitempty"`
	IsStreaming           bool                   `protobuf:"varint,3,opt,name=is_streaming,json=isStreaming,proto3" json:"is_streaming,omitempty"`
	IsCompacting          bool                   `protobuf:"varint,4,opt,name=is_compacting,json=isCompacting,proto3" json:"is_compacting,omitempty"`
	SteeringMode          string                 `protobuf:"bytes,5,opt,name=steering_mode,json=steeringMode,proto3" json:"steering_mode,omitempty"`
	FollowUpMode          string                 `protobuf:"bytes,6,opt,name=follow_up_mode,json=followUpMode,proto3" json:"follow_up_mode,omitempty"`
	SessionFile           *string                `protobuf:"bytes,7,opt,name=session_file,json=sessionFile,proto3,oneof" json:"session_file,omitempty"`
	SessionId             string                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionName           *string                `protobuf:"bytes,9,opt,name=session_name,json=sessionName,proto3,oneof" json:"session_name,omitempty"`
	AutoCompactionEnabled bool                   `protobuf:"varint,10,opt,name=auto_compaction_enabled,json=autoCompactionEnabled,proto3" json:"auto_compaction_enabled,omitempty"`
	MessageCount          uint32                 `protobuf:"varint,11,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	PendingMessageCount   uint32                 `protobuf:"varint,12,opt,name=pending_message_count,json=pendingMessageCount,proto3" json:"pending_message_count,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SessionState) Reset() {
	*x = SessionState{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionState) ProtoMessage() {}

func (x *SessionState) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionState.ProtoReflect.Descriptor instead.
func (*SessionState) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{16}
}

func (x *SessionState) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *SessionState) GetThinkingLevel() string {
	if x != nil {
		return x.ThinkingLevel
	}
	return ""
}

func (x *SessionState) GetIsStreaming() bool {
	if x != nil {
		return x.IsStreaming
	}
	return false
}

func (x *SessionState) GetIsCompacting() bool {
	if x != nil {
		return x.IsCompacting
	}
	return false
}

func (x *SessionState) GetSteeringMode() string {
	if x != nil {
		return x.SteeringMode
	}
	return ""
}

func (x *SessionState) GetFollowUpMode() string {
	if x != nil {
		return x.FollowUpMode
	}
	return ""
}

func (x *SessionState) GetSessionFile() string {
	if x != nil && x.SessionFile != nil {
		return *x.SessionFile
	}
	return ""
}

func (x *SessionState) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionState) GetSessionName() string {
	if x != nil && x.SessionName != nil {
		return *x.SessionName
	}
	return ""
}

func (x *SessionState) GetAutoCompactionEnabled() bool {
	if x != nil {
		return x.AutoCompactionEnabled
	}
	return false
}

func (x *SessionState) GetMessageCount() uint32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

func (x *SessionState) GetPendingMessageCount() uint32 {
	if x != nil {
		return x.PendingMessageCount
	}
	return 0
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Api           string                 `protobuf:"bytes,3,opt,name=api,proto3" json:"api,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,5,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Reasoning     bool                   `protobuf:"varint,6,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Input         []string               `protobuf:"bytes,7,rep,name=input,proto3" json:"input,omitempty"`
	Cost          *ModelCost             `protobuf:"bytes,8,opt,name=cost,proto3" json:"cost,omitempty"`
	ContextWindow uint32                 `protobuf:"varint,9,opt,name=context_window,json=contextWindow,proto3" json:"context_window,omitempty"`
	MaxTokens     uint32                 `protobuf:"varint,10,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{17}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *Model) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Model) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *Model) GetReasoning() bool {
	if x != nil {
		return x.Reasoning
	}
	return false
}

func (x *Model) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Model) GetCost() *ModelCost {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *Model) GetContextWindow() uint32 {
	if x != nil {
		return x.ContextWindow
	}
	return 0
}

func (x *Model) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type ModelCost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         float64                `protobuf:"fixed64,1,opt,name=input,proto3" json:"input,omitempty"`
	Output        float64                `protobuf:"fixed64,2,opt,name=output,proto3" json:"output,omitempty"`
	CacheRead     float64                `protobuf:"fixed64,3,opt,name=cache_read,json=cacheRead,proto3" json:"cache_read,omitempty"`
	CacheWrite    float64                `protobuf:"fixed64,4,opt,name=cache_write,json=cacheWrite,proto3" json:"cache_write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelCost) Reset() {
	*x = ModelCost{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelCost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCost) ProtoMessage() {}

func (x *ModelCost) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCost.ProtoReflect.Descriptor instead.
func (*ModelCost) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{18}
}

func (x *ModelCost) GetInput() float64 {
	if x != nil {
		return x.Input
	}
	return 0
}

func (x *ModelCost) GetOutput() float64 {
	if x != nil {
		return x.Output
	}
	return 0
}

func (x *ModelCost) GetCacheRead() float64 {
	if x != nil {
		return x.CacheRead
	}
	return 0
}

func (x *ModelCost) GetCacheWrite() float64 {
	if x != nil {
		return x.CacheWrite
	}
	return 0
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{19}
}

type SessionSwitchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cancelled     bool                   `protobuf:"varint,1,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSwitchResult) Reset() {
	*x = SessionSwitchResult{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSwitchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSwitchResult) ProtoMessage() {}

func (x *SessionSwitchResult) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSwitchResult.ProtoReflect.Descriptor instead.
func (*SessionSwitchResult) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{20}
}

func (x *SessionSwitchResult) GetCancelled() bool {
	if x != nil {
		return x.Cancelled
	}
	return false
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*AgentMessage        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{21}
}

func (x *GetMessagesResponse) GetMessages() []*AgentMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          []byte                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	Blob          *BlobRef               `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{22}
}

func (x *Payload) GetJson() []byte {
	if x != nil {
		return x.Json
	}
	return nil
}

func (x *Payload) GetBlob() *BlobRef {
	if x != nil {
		return x.Blob
	}
	return nil
}

type BlobRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlobId        string                 `protobuf:"bytes,1,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	TotalBytes    uint64                 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobRef) Reset() {
	*x = BlobRef{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobRef) ProtoMessage() {}

func (x *BlobRef) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobRef.ProtoReflect.Descriptor instead.
func (*BlobRef) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{23}
}

func (x *BlobRef) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *BlobRef) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type AgentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Payload       *Payload               `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{24}
}

func (x *AgentMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AgentMessage) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Events        []*Event               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{25}
}

func (x *EventBatch) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EventBatch) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload         *Payload               `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	SessionBoundary *SessionBoundary       `protobuf:"bytes,3,opt,name=session_boundary,json=sessionBoundary,proto3" json:"session_boundary,omitempty"`
	Sequence        uint64                 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{26}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPayload() *Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetSessionBoundary() *SessionBoundary {
	if x != nil {
		return x.SessionBoundary
	}
	return nil
}

func (x *Event) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type SessionBoundary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionFile   *string                `protobuf:"bytes,2,opt,name=session_file,json=sessionFile,proto3,oneof" json:"session_file,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionBoundary) Reset() {
	*x = SessionBoundary{}
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionBoundary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionBoundary) ProtoMessage() {}

func (x *SessionBoundary) ProtoReflect() protoreflect.Message {
	mi := &file_pi_agent_v1_pi_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionBoundary.ProtoReflect.Descriptor instead.
func (*SessionBoundary) Descriptor() ([]byte, []int) {
	return file_pi_agent_v1_pi_agent_proto_rawDescGZIP(), []int{27}
}

func (x *SessionBoundary) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionBoundary) GetSessionFile() string {
	if x != nil && x.SessionFile != nil {
		return *x.SessionFile
	}
	return ""
}

func (x *SessionBoundary) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_pi_agent_v1_pi_agent_proto protoreflect.FileDescriptor

const file_pi_agent_v1_pi_agent_proto_rawDesc = "" +
	"\n" +
	"\x1api/agent/v1/pi_agent.proto\x12\vpi.agent.v1\"\x11\n" +
	"\x0fGetStateRequest\"i\n" +
	"\x12GetMessagesRequest\x12'\n" +
	"\x0finline_payloads\x18\x01 \x01(\bR\x0einlinePayloads\x12*\n" +
	"\x11inline_byte_limit\x18\x02 \x01(\rR\x0finlineByteLimit\"X\n" +
	"\x0fReadBlobRequest\x12\x17\n" +
	"\ablob_id\x18\x01 \x01(\tR\x06blobId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"\x8a\x01\n" +
	"\x10ReadBlobResponse\x12\x17\n" +
	"\ablob_id\x18\x01 \x01(\tR\x06blobId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12\x10\n" +
	"\x03eof\x18\x05 \x01(\bR\x03eof\"\xa4\x01\n" +
	"\rPromptRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12*\n" +
	"\x06images\x18\x02 \x03(\v2\x12.pi.agent.v1.ImageR\x06images\x12M\n" +
	"\x12streaming_behavior\x18\x03 \x01(\x0e2\x1e.pi.agent.v1.StreamingBehaviorR\x11streamingBehavior\"T\n" +
	"\fSteerRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12*\n" +
	"\x06images\x18\x02 \x03(\v2\x12.pi.agent.v1.ImageR\x06images\"W\n" +
	"\x0fFollowUpRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12*\n" +
	"\x06images\x18\x02 \x03(\v2\x12.pi.agent.v1.ImageR\x06images\"\x0e\n" +
	"\fAbortRequest\"R\n" +
	"\x11NewSessionRequest\x12*\n" +
	"\x0eparent_session\x18\x01 \x01(\tH\x00R\rparentSession\x88\x01\x01B\x11\n" +
	"\x0f_parent_session\"\x15\n" +
	"\x13ListCommandsRequest\"?\n" +
	"\x15ExecuteCommandRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x01(\tR\x04args\"M\n" +
	"\x14ListCommandsResponse\x125\n" +
	"\bcommands\x18\x01 \x03(\v2\x19.pi.agent.v1.SlashCommandR\bcommands\"\x96\x01\n" +
	"\fSlashCommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x128\n" +
	"\vsource_info\x18\x04 \x01(\v2\x17.pi.agent.v1.SourceInfoR\n" +
	"sourceInfo\"\x81\x01\n" +
	"\n" +
	"SourceInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\tR\x06origin\x12\x19\n" +
	"\bbase_dir\x18\x05 \x01(\tR\abaseDir\"\x91\x02\n" +
	"\x16SubscribeEventsRequest\x12-\n" +
	"\x05level\x18\x01 \x01(\x0e2\x17.pi.agent.v1.EventLevelR\x05level\x12&\n" +
	"\x0fbatch_window_ms\x18\x02 \x01(\rR\rbatchWindowMs\x12$\n" +
	"\x0emax_batch_size\x18\x03 \x01(\rR\fmaxBatchSize\x12%\n" +
	"\x0eafter_sequence\x18\x04 \x01(\x04R\rafterSequence\x12'\n" +
	"\x0finline_payloads\x18\x05 \x01(\bR\x0einlinePayloads\x12*\n" +
	"\x11inline_byte_limit\x18\x06 \x01(\rR\x0finlineByteLimit\"8\n" +
	"\x05Image\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"\xa3\x04\n" +
	"\fSessionState\x12-\n" +
	"\x05model\x18\x01 \x01(\v2\x12.pi.agent.v1.ModelH\x00R\x05model\x88\x01\x01\x12%\n" +
	"\x0ethinking_level\x18\x02 \x01(\tR\rthinkingLevel\x12!\n" +
	"\fis_streaming\x18\x03 \x01(\bR\visStreaming\x12#\n" +
	"\ris_compacting\x18\x04 \x01(\bR\fisCompacting\x12#\n" +
	"\rsteering_mode\x18\x05 \x01(\tR\fsteeringMode\x12$\n" +
	"\x0efollow_up_mode\x18\x06 \x01(\tR\ffollowUpMode\x12&\n" +
	"\fsession_file\x18\a \x01(\tH\x01R\vsessionFile\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\x12&\n" +
	"\fsession_name\x18\t \x01(\tH\x02R\vsessionName\x88\x01\x01\x126\n" +
	"\x17auto_compaction_enabled\x18\n" +
	" \x01(\bR\x15autoCompactionEnabled\x12#\n" +
	"\rmessage_count\x18\v \x01(\rR\fmessageCount\x122\n" +
	"\x15pending_message_count\x18\f \x01(\rR\x13pendingMessageCountB\b\n" +
	"\x06_modelB\x0f\n" +
	"\r_session_fileB\x0f\n" +
	"\r_session_name\"\x9a\x02\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03api\x18\x03 \x01(\tR\x03api\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12\x19\n" +
	"\bbase_url\x18\x05 \x01(\tR\abaseUrl\x12\x1c\n" +
	"\treasoning\x18\x06 \x01(\bR\treasoning\x12\x14\n" +
	"\x05input\x18\a \x03(\tR\x05input\x12*\n" +
	"\x04cost\x18\b \x01(\v2\x16.pi.agent.v1.ModelCostR\x04cost\x12%\n" +
	"\x0econtext_window\x18\t \x01(\rR\rcontextWindow\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\n" +
	" \x01(\rR\tmaxTokens\"y\n" +
	"\tModelCost\x12\x14\n" +
	"\x05input\x18\x01 \x01(\x01R\x05input\x12\x16\n" +
	"\x06output\x18\x02 \x01(\x01R\x06output\x12\x1d\n" +
	"\n" +
	"cache_read\x18\x03 \x01(\x01R\tcacheRead\x12\x1f\n" +
	"\vcache_write\x18\x04 \x01(\x01R\n" +
	"cacheWrite\"\f\n" +
	"\n" +
	"CommandAck\"3\n" +
	"\x13SessionSwitchResult\x12\x1c\n" +
	"\tcancelled\x18\x01 \x01(\bR\tcancelled\"L\n" +
	"\x13GetMessagesResponse\x125\n" +
	"\bmessages\x18\x01 \x03(\v2\x19.pi.agent.v1.AgentMessageR\bmessages\"G\n" +
	"\aPayload\x12\x12\n" +
	"\x04json\x18\x01 \x01(\fR\x04json\x12(\n" +
	"\x04blob\x18\x02 \x01(\v2\x14.pi.agent.v1.BlobRefR\x04blob\"C\n" +
	"\aBlobRef\x12\x17\n" +
	"\ablob_id\x18\x01 \x01(\tR\x06blobId\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x04R\n" +
	"totalBytes\"R\n" +
	"\fAgentMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.pi.agent.v1.PayloadR\apayload\"T\n" +
	"\n" +
	"EventBatch\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12*\n" +
	"\x06events\x18\x02 \x03(\v2\x12.pi.agent.v1.EventR\x06events\"\xb0\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12.\n" +
	"\apayload\x18\x02 \x01(\v2\x14.pi.agent.v1.PayloadR\apayload\x12G\n" +
	"\x10session_boundary\x18\x03 \x01(\v2\x1c.pi.agent.v1.SessionBoundaryR\x0fsessionBoundary\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\"\x81\x01\n" +
	"\x0fSessionBoundary\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12&\n" +
	"\fsession_file\x18\x02 \x01(\tH\x00R\vsessionFile\x88\x01\x01\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reasonB\x0f\n" +
	"\r_session_file*w\n" +
	"\x11StreamingBehavior\x12\"\n" +
	"\x1eSTREAMING_BEHAVIOR_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18STREAMING_BEHAVIOR_STEER\x10\x01\x12 \n" +
	"\x1cSTREAMING_BEHAVIOR_FOLLOW_UP\x10\x02*h\n" +
	"\n" +
	"EventLevel\x12\x17\n" +
	"\x13EVENT_LEVEL_SUMMARY\x10\x00\x12\x14\n" +
	"\x10EVENT_LEVEL_NONE\x10\x01\x12\x15\n" +
	"\x11EVENT_LEVEL_STATE\x10\x02\x12\x14\n" +
	"\x10EVENT_LEVEL_FULL\x10\x032\xac\x06\n" +
	"\aPiAgent\x12C\n" +
	"\bGetState\x12\x1c.pi.agent.v1.GetStateRequest\x1a\x19.pi.agent.v1.SessionState\x12=\n" +
	"\x06Prompt\x12\x1a.pi.agent.v1.PromptRequest\x1a\x17.pi.agent.v1.CommandAck\x12;\n" +
	"\x05Steer\x12\x19.pi.agent.v1.SteerRequest\x1a\x17.pi.agent.v1.CommandAck\x12A\n" +
	"\bFollowUp\x12\x1c.pi.agent.v1.FollowUpRequest\x1a\x17.pi.agent.v1.CommandAck\x12;\n" +
	"\x05Abort\x12\x19.pi.agent.v1.AbortRequest\x1a\x17.pi.agent.v1.CommandAck\x12N\n" +
	"\n" +
	"NewSession\x12\x1e.pi.agent.v1.NewSessionRequest\x1a .pi.agent.v1.SessionSwitchResult\x12S\n" +
	"\fListCommands\x12 .pi.agent.v1.ListCommandsRequest\x1a!.pi.agent.v1.ListCommandsResponse\x12M\n" +
	"\x0eExecuteCommand\x12\".pi.agent.v1.ExecuteCommandRequest\x1a\x17.pi.agent.v1.CommandAck\x12P\n" +
	"\vGetMessages\x12\x1f.pi.agent.v1.GetMessagesRequest\x1a .pi.agent.v1.GetMessagesResponse\x12G\n" +
	"\bReadBlob\x12\x1c.pi.agent.v1.ReadBlobRequest\x1a\x1d.pi.agent.v1.ReadBlobResponse\x12Q\n" +
	"\x0fSubscribeEvents\x12#.pi.agent.v1.SubscribeEventsRequest\x1a\x17.pi.agent.v1.EventBatch0\x01B%Z#actrail/proto/pi/agent/v1;piagentv1b\x06proto3"

var (
	file_pi_agent_v1_pi_agent_proto_rawDescOnce sync.Once
	file_pi_agent_v1_pi_agent_proto_rawDescData []byte
)

func file_pi_agent_v1_pi_agent_proto_rawDescGZIP() []byte {
	file_pi_agent_v1_pi_agent_proto_rawDescOnce.Do(func() {
		file_pi_agent_v1_pi_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pi_agent_v1_pi_agent_proto_rawDesc), len(file_pi_agent_v1_pi_agent_proto_rawDesc)))
	})
	return file_pi_agent_v1_pi_agent_proto_rawDescData
}

var file_pi_agent_v1_pi_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pi_agent_v1_pi_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_pi_agent_v1_pi_agent_proto_goTypes = []any{
	(StreamingBehavior)(0),         // 0: pi.agent.v1.StreamingBehavior
	(EventLevel)(0),                // 1: pi.agent.v1.EventLevel
	(*GetStateRequest)(nil),        // 2: pi.agent.v1.GetStateRequest
	(*GetMessagesRequest)(nil),     // 3: pi.agent.v1.GetMessagesRequest
	(*ReadBlobRequest)(nil),        // 4: pi.agent.v1.ReadBlobRequest
	(*ReadBlobResponse)(nil),       // 5: pi.agent.v1.ReadBlobResponse
	(*PromptRequest)(nil),          // 6: pi.agent.v1.PromptRequest
	(*SteerRequest)(nil),           // 7: pi.agent.v1.SteerRequest
	(*FollowUpRequest)(nil),        // 8: pi.agent.v1.FollowUpRequest
	(*AbortRequest)(nil),           // 9: pi.agent.v1.AbortRequest
	(*NewSessionRequest)(nil),      // 10: pi.agent.v1.NewSessionRequest
	(*ListCommandsRequest)(nil),    // 11: pi.agent.v1.ListCommandsRequest
	(*ExecuteCommandRequest)(nil),  // 12: pi.agent.v1.ExecuteCommandRequest
	(*ListCommandsResponse)(nil),   // 13: pi.agent.v1.ListCommandsResponse
	(*SlashCommand)(nil),           // 14: pi.agent.v1.SlashCommand
	(*SourceInfo)(nil),             // 15: pi.agent.v1.SourceInfo
	(*SubscribeEventsRequest)(nil), // 16: pi.agent.v1.SubscribeEventsRequest
	(*Image)(nil),                  // 17: pi.agent.v1.Image
	(*SessionState)(nil),           // 18: pi.agent.v1.SessionState
	(*Model)(nil),                  // 19: pi.agent.v1.Model
	(*ModelCost)(nil),              // 20: pi.agent.v1.ModelCost
	(*CommandAck)(nil),             // 21: pi.agent.v1.CommandAck
	(*SessionSwitchResult)(nil),    // 22: pi.agent.v1.SessionSwitchResult
	(*GetMessagesResponse)(nil),    // 23: pi.agent.v1.GetMessagesResponse
	(*Payload)(nil),                // 24: pi.agent.v1.Payload
	(*BlobRef)(nil),                // 25: pi.agent.v1.BlobRef
	(*AgentMessage)(nil),           // 26: pi.agent.v1.AgentMessage
	(*EventBatch)(nil),             // 27: pi.agent.v1.EventBatch
	(*Event)(nil),                  // 28: pi.agent.v1.Event
	(*SessionBoundary)(nil),        // 29: pi.agent.v1.SessionBoundary
}
var file_pi_agent_v1_pi_agent_proto_depIdxs = []int32{
	17, // 0: pi.agent.v1.PromptRequest.images:type_name -> pi.agent.v1.Image
	0,  // 1: pi.agent.v1.PromptRequest.streaming_behavior:type_name -> pi.agent.v1.StreamingBehavior
	17, // 2: pi.agent.v1.SteerRequest.images:type_name -> pi.agent.v1.Image
	17, // 3: pi.agent.v1.FollowUpRequest.images:type_name -> pi.agent.v1.Image
	14, // 4: pi.agent.v1.ListCommandsResponse.commands:type_name -> pi.agent.v1.SlashCommand
	15, // 5: pi.agent.v1.SlashCommand.source_info:type_name -> pi.agent.v1.SourceInfo
	1,  // 6: pi.agent.v1.SubscribeEventsRequest.level:type_name -> pi.agent.v1.EventLevel
	19, // 7: pi.agent.v1.SessionState.model:type_name -> pi.agent.v1.Model
	20, // 8: pi.agent.v1.Model.cost:type_name -> pi.agent.v1.ModelCost
	26, // 9: pi.agent.v1.GetMessagesResponse.messages:type_name -> pi.agent.v1.AgentMessage
	25, // 10: pi.agent.v1.Payload.blob:type_name -> pi.agent.v1.BlobRef
	24, // 11: pi.agent.v1.AgentMessage.payload:type_name -> pi.agent.v1.Payload
	28, // 12: pi.agent.v1.EventBatch.events:type_name -> pi.agent.v1.Event
	24, // 13: pi.agent.v1.Event.payload:type_name -> pi.agent.v1.Payload
	29, // 14: pi.agent.v1.Event.session_boundary:type_name -> pi.agent.v1.SessionBoundary
	2,  // 15: pi.agent.v1.PiAgent.GetState:input_type -> pi.agent.v1.GetStateRequest
	6,  // 16: pi.agent.v1.PiAgent.Prompt:input_type -> pi.agent.v1.PromptRequest
	7,  // 17: pi.agent.v1.PiAgent.Steer:input_type -> pi.agent.v1.SteerRequest
	8,  // 18: pi.agent.v1.PiAgent.FollowUp:input_type -> pi.agent.v1.FollowUpRequest
	9,  // 19: pi.agent.v1.PiAgent.Abort:input_type -> pi.agent.v1.AbortRequest
	10, // 20: pi.agent.v1.PiAgent.NewSession:input_type -> pi.agent.v1.NewSessionRequest
	11, // 21: pi.agent.v1.PiAgent.ListCommands:input_type -> pi.agent.v1.ListCommandsRequest
	12, // 22: pi.agent.v1.PiAgent.ExecuteCommand:input_type -> pi.agent.v1.ExecuteCommandRequest
	3,  // 23: pi.agent.v1.PiAgent.GetMessages:input_type -> pi.agent.v1.GetMessagesRequest
	4,  // 24: pi.agent.v1.PiAgent.ReadBlob:input_type -> pi.agent.v1.ReadBlobRequest
	16, // 25: pi.agent.v1.PiAgent.SubscribeEvents:input_type -> pi.agent.v1.SubscribeEventsRequest
	18, // 26: pi.agent.v1.PiAgent.GetState:output_type -> pi.agent.v1.SessionState
	21, // 27: pi.agent.v1.PiAgent.Prompt:output_type -> pi.agent.v1.CommandAck
	21, // 28: pi.agent.v1.PiAgent.Steer:output_type -> pi.agent.v1.CommandAck
	21, // 29: pi.agent.v1.PiAgent.FollowUp:output_type -> pi.agent.v1.CommandAck
	21, // 30: pi.agent.v1.PiAgent.Abort:output_type -> pi.agent.v1.CommandAck
	22, // 31: pi.agent.v1.PiAgent.NewSession:output_type -> pi.agent.v1.SessionSwitchResult
	13, // 32: pi.agent.v1.PiAgent.ListCommands:output_type -> pi.agent.v1.ListCommandsResponse
	21, // 33: pi.agent.v1.PiAgent.ExecuteCommand:output_type -> pi.agent.v1.CommandAck
	23, // 34: pi.agent.v1.PiAgent.GetMessages:output_type -> pi.agent.v1.GetMessagesResponse
	5,  // 35: pi.agent.v1.PiAgent.ReadBlob:output_type -> pi.agent.v1.ReadBlobResponse
	27, // 36: pi.agent.v1.PiAgent.SubscribeEvents:output_type -> pi.agent.v1.EventBatch
	26, // [26:37] is the sub-list for method output_type
	15, // [15:26] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pi_agent_v1_pi_agent_proto_init() }
func file_pi_agent_v1_pi_agent_proto_init() {
	if File_pi_agent_v1_pi_agent_proto != nil {
		return
	}
	file_pi_agent_v1_pi_agent_proto_msgTypes[8].OneofWrappers = []any{}
	file_pi_agent_v1_pi_agent_proto_msgTypes[16].OneofWrappers = []any{}
	file_pi_agent_v1_pi_agent_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pi_agent_v1_pi_agent_proto_rawDesc), len(file_pi_agent_v1_pi_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pi_agent_v1_pi_agent_proto_goTypes,
		DependencyIndexes: file_pi_agent_v1_pi_agent_proto_depIdxs,
		EnumInfos:         file_pi_agent_v1_pi_agent_proto_enumTypes,
		MessageInfos:      file_pi_agent_v1_pi_agent_proto_msgTypes,
	}.Build()
	File_pi_agent_v1_pi_agent_proto = out.File
	file_pi_agent_v1_pi_agent_proto_goTypes = nil
	file_pi_agent_v1_pi_agent_proto_depIdxs = nil
}
