// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: actrail/v1/transport.proto

package actrailv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RuntimeId     string                 `protobuf:"bytes,2,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionIdentity) Reset() {
	*x = SessionIdentity{}
	mi := &file_actrail_v1_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionIdentity) ProtoMessage() {}

func (x *SessionIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_actrail_v1_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionIdentity.ProtoReflect.Descriptor instead.
func (*SessionIdentity) Descriptor() ([]byte, []int) {
	return file_actrail_v1_transport_proto_rawDescGZIP(), []int{0}
}

func (x *SessionIdentity) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionIdentity) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionIdentity       `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_actrail_v1_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actrail_v1_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_actrail_v1_transport_proto_rawDescGZIP(), []int{1}
}

func (x *SendRequest) GetSession() *SessionIdentity {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *SendRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EnqueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionIdentity       `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_actrail_v1_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actrail_v1_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_actrail_v1_transport_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueueRequest) GetSession() *SessionIdentity {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *EnqueueRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CancelQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionIdentity       `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueueRequest) Reset() {
	*x = CancelQueueRequest{}
	mi := &file_actrail_v1_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueueRequest) ProtoMessage() {}

func (x *CancelQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actrail_v1_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueueRequest.ProtoReflect.Descriptor instead.
func (*CancelQueueRequest) Descriptor() ([]byte, []int) {
	return file_actrail_v1_transport_proto_rawDescGZIP(), []int{3}
}

func (x *CancelQueueRequest) GetSession() *SessionIdentity {
	if x != nil {
		return x.Session
	}
	return nil
}

type InterruptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionIdentity       `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptRequest) Reset() {
	*x = InterruptRequest{}
	mi := &file_actrail_v1_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptRequest) ProtoMessage() {}

func (x *InterruptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actrail_v1_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptRequest.ProtoReflect.Descriptor instead.
func (*InterruptRequest) Descriptor() ([]byte, []int) {
	return file_actrail_v1_transport_proto_rawDescGZIP(), []int{4}
}

func (x *InterruptRequest) GetSession() *SessionIdentity {
	if x != nil {
		return x.Session
	}
	return nil
}

type RespondUIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionIdentity       `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ResponseTo    string                 `protobuf:"bytes,2,opt,name=response_to,json=responseTo,proto3" json:"response_to,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondUIRequest) Reset() {
	*x = RespondUIRequest{}
	mi := &file_actrail_v1_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondUIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondUIRequest) ProtoMessage() {}

func (x *RespondUIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actrail_v1_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondUIRequest.ProtoReflect.Descriptor instead.
func (*RespondUIRequest) Descriptor() ([]byte, []int) {
	return file_actrail_v1_transport_proto_rawDescGZIP(), []int{5}
}

func (x *RespondUIRequest) GetSession() *SessionIdentity {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *RespondUIRequest) GetResponseTo() string {
	if x != nil {
		return x.ResponseTo
	}
	return ""
}

func (x *RespondUIRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadJson   []byte                 `protobuf:"bytes,1,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_actrail_v1_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_actrail_v1_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_actrail_v1_transport_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResponse) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfterEventId  uint64                 `protobuf:"varint,1,opt,name=after_event_id,json=afterEventId,proto3" json:"after_event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_actrail_v1_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actrail_v1_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_actrail_v1_transport_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeRequest) GetAfterEventId() uint64 {
	if x != nil {
		return x.AfterEventId
	}
	return 0
}

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Stream        string                 `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	UnixMillis    int64                  `protobuf:"varint,4,opt,name=unix_millis,json=unixMillis,proto3" json:"unix_millis,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_actrail_v1_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_actrail_v1_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_actrail_v1_transport_proto_rawDescGZIP(), []int{8}
}

func (x *EventEnvelope) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EventEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventEnvelope) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *EventEnvelope) GetUnixMillis() int64 {
	if x != nil {
		return x.UnixMillis
	}
	return 0
}

func (x *EventEnvelope) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

type SessionMessagesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AfterSeq           *uint64                `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3,oneof" json:"after_seq,omitempty"`
	BeforeSeq          *uint64                `protobuf:"varint,3,opt,name=before_seq,json=beforeSeq,proto3,oneof" json:"before_seq,omitempty"`
	Limit              int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Init               bool                   `protobuf:"varint,5,opt,name=init,proto3" json:"init,omitempty"`
	Deferred           bool                   `protobuf:"varint,6,opt,name=deferred,proto3" json:"deferred,omitempty"`
	ActiveTurnStartSeq uint64                 `protobuf:"varint,7,opt,name=active_turn_start_seq,json=activeTurnStartSeq,proto3" json:"active_turn_start_seq,omitempty"`
	IncludeToolDetails bool                   `protobuf:"varint,8,opt,name=include_tool_details,json=includeToolDetails,proto3" json:"include_tool_details,omitempty"`
	EventId            string                 `protobuf:"bytes,9,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ToolCallId         string                 `protobuf:"bytes,10,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SessionMessagesRequest) Reset() {
	*x = SessionMessagesRequest{}
	mi := &file_actrail_v1_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessagesRequest) ProtoMessage() {}

func (x *SessionMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_actrail_v1_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessagesRequest.ProtoReflect.Descriptor instead.
func (*SessionMessagesRequest) Descriptor() ([]byte, []int) {
	return file_actrail_v1_transport_proto_rawDescGZIP(), []int{9}
}

func (x *SessionMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionMessagesRequest) GetAfterSeq() uint64 {
	if x != nil && x.AfterSeq != nil {
		return *x.AfterSeq
	}
	return 0
}

func (x *SessionMessagesRequest) GetBeforeSeq() uint64 {
	if x != nil && x.BeforeSeq != nil {
		return *x.BeforeSeq
	}
	return 0
}

func (x *SessionMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SessionMessagesRequest) GetInit() bool {
	if x != nil {
		return x.Init
	}
	return false
}

func (x *SessionMessagesRequest) GetDeferred() bool {
	if x != nil {
		return x.Deferred
	}
	return false
}

func (x *SessionMessagesRequest) GetActiveTurnStartSeq() uint64 {
	if x != nil {
		return x.ActiveTurnStartSeq
	}
	return 0
}

func (x *SessionMessagesRequest) GetIncludeToolDetails() bool {
	if x != nil {
		return x.IncludeToolDetails
	}
	return false
}

func (x *SessionMessagesRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *SessionMessagesRequest) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

type SessionMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventsJson    [][]byte               `protobuf:"bytes,1,rep,name=events_json,json=eventsJson,proto3" json:"events_json,omitempty"`
	TailSeq       uint64                 `protobuf:"varint,2,opt,name=tail_seq,json=tailSeq,proto3" json:"tail_seq,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextBeforeSeq *uint64                `protobuf:"varint,4,opt,name=next_before_seq,json=nextBeforeSeq,proto3,oneof" json:"next_before_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessagesResponse) Reset() {
	*x = SessionMessagesResponse{}
	mi := &file_actrail_v1_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessagesResponse) ProtoMessage() {}

func (x *SessionMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_actrail_v1_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessagesResponse.ProtoReflect.Descriptor instead.
func (*SessionMessagesResponse) Descriptor() ([]byte, []int) {
	return file_actrail_v1_transport_proto_rawDescGZIP(), []int{10}
}

func (x *SessionMessagesResponse) GetEventsJson() [][]byte {
	if x != nil {
		return x.EventsJson
	}
	return nil
}

func (x *SessionMessagesResponse) GetTailSeq() uint64 {
	if x != nil {
		return x.TailSeq
	}
	return 0
}

func (x *SessionMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *SessionMessagesResponse) GetNextBeforeSeq() uint64 {
	if x != nil && x.NextBeforeSeq != nil {
		return *x.NextBeforeSeq
	}
	return 0
}

var File_actrail_v1_transport_proto protoreflect.FileDescriptor

const file_actrail_v1_transport_proto_rawDesc = "" +
	"\n" +
	"\x1aactrail/v1/transport.proto\x12\n" +
	"actrail.v1\"O\n" +
	"\x0fSessionIdentity\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x02 \x01(\tR\truntimeId\"X\n" +
	"\vSendRequest\x125\n" +
	"\asession\x18\x01 \x01(\v2\x1b.actrail.v1.SessionIdentityR\asession\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"[\n" +
	"\x0eEnqueueRequest\x125\n" +
	"\asession\x18\x01 \x01(\v2\x1b.actrail.v1.SessionIdentityR\asession\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"K\n" +
	"\x12CancelQueueRequest\x125\n" +
	"\asession\x18\x01 \x01(\v2\x1b.actrail.v1.SessionIdentityR\asession\"I\n" +
	"\x10InterruptRequest\x125\n" +
	"\asession\x18\x01 \x01(\v2\x1b.actrail.v1.SessionIdentityR\asession\"\x80\x01\n" +
	"\x10RespondUIRequest\x125\n" +
	"\asession\x18\x01 \x01(\v2\x1b.actrail.v1.SessionIdentityR\asession\x12\x1f\n" +
	"\vresponse_to\x18\x02 \x01(\tR\n" +
	"responseTo\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"4\n" +
	"\x0fCommandResponse\x12!\n" +
	"\fpayload_json\x18\x01 \x01(\fR\vpayloadJson\"8\n" +
	"\x10SubscribeRequest\x12$\n" +
	"\x0eafter_event_id\x18\x01 \x01(\x04R\fafterEventId\"\x8f\x01\n" +
	"\rEventEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\tR\x06stream\x12\x1f\n" +
	"\vunix_millis\x18\x04 \x01(\x03R\n" +
	"unixMillis\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\fR\vpayloadJson\"\x82\x03\n" +
	"\x16SessionMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12 \n" +
	"\tafter_seq\x18\x02 \x01(\x04H\x00R\bafterSeq\x88\x01\x01\x12\"\n" +
	"\n" +
	"before_seq\x18\x03 \x01(\x04H\x01R\tbeforeSeq\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04init\x18\x05 \x01(\bR\x04init\x12\x1a\n" +
	"\bdeferred\x18\x06 \x01(\bR\bdeferred\x121\n" +
	"\x15active_turn_start_seq\x18\a \x01(\x04R\x12activeTurnStartSeq\x120\n" +
	"\x14include_tool_details\x18\b \x01(\bR\x12includeToolDetails\x12\x19\n" +
	"\bevent_id\x18\t \x01(\tR\aeventId\x12 \n" +
	"\ftool_call_id\x18\n" +
	" \x01(\tR\n" +
	"toolCallIdB\f\n" +
	"\n" +
	"_after_seqB\r\n" +
	"\v_before_seq\"\xb1\x01\n" +
	"\x17SessionMessagesResponse\x12\x1f\n" +
	"\vevents_json\x18\x01 \x03(\fR\n" +
	"eventsJson\x12\x19\n" +
	"\btail_seq\x18\x02 \x01(\x04R\atailSeq\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12+\n" +
	"\x0fnext_before_seq\x18\x04 \x01(\x04H\x00R\rnextBeforeSeq\x88\x01\x01B\x12\n" +
	"\x10_next_before_seq2\xd1\x03\n" +
	"\x15SessionCommandService\x12<\n" +
	"\x04Send\x12\x17.actrail.v1.SendRequest\x1a\x1b.actrail.v1.CommandResponse\x12B\n" +
	"\aEnqueue\x12\x1a.actrail.v1.EnqueueRequest\x1a\x1b.actrail.v1.CommandResponse\x12J\n" +
	"\vCancelQueue\x12\x1e.actrail.v1.CancelQueueRequest\x1a\x1b.actrail.v1.CommandResponse\x12F\n" +
	"\tInterrupt\x12\x1c.actrail.v1.InterruptRequest\x1a\x1b.actrail.v1.CommandResponse\x12F\n" +
	"\tRespondUI\x12\x1c.actrail.v1.RespondUIRequest\x1a\x1b.actrail.v1.CommandResponse\x12Z\n" +
	"\x0fSessionMessages\x12\".actrail.v1.SessionMessagesRequest\x1a#.actrail.v1.SessionMessagesResponse2V\n" +
	"\fEventService\x12F\n" +
	"\tSubscribe\x12\x1c.actrail.v1.SubscribeRequest\x1a\x19.actrail.v1.EventEnvelope0\x01B$Z\"actrail/proto/actrail/v1;actrailv1b\x06proto3"

var (
	file_actrail_v1_transport_proto_rawDescOnce sync.Once
	file_actrail_v1_transport_proto_rawDescData []byte
)

func file_actrail_v1_transport_proto_rawDescGZIP() []byte {
	file_actrail_v1_transport_proto_rawDescOnce.Do(func() {
		file_actrail_v1_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actrail_v1_transport_proto_rawDesc), len(file_actrail_v1_transport_proto_rawDesc)))
	})
	return file_actrail_v1_transport_proto_rawDescData
}

var file_actrail_v1_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_actrail_v1_transport_proto_goTypes = []any{
	(*SessionIdentity)(nil),         // 0: actrail.v1.SessionIdentity
	(*SendRequest)(nil),             // 1: actrail.v1.SendRequest
	(*EnqueueRequest)(nil),          // 2: actrail.v1.EnqueueRequest
	(*CancelQueueRequest)(nil),      // 3: actrail.v1.CancelQueueRequest
	(*InterruptRequest)(nil),        // 4: actrail.v1.InterruptRequest
	(*RespondUIRequest)(nil),        // 5: actrail.v1.RespondUIRequest
	(*CommandResponse)(nil),         // 6: actrail.v1.CommandResponse
	(*SubscribeRequest)(nil),        // 7: actrail.v1.SubscribeRequest
	(*EventEnvelope)(nil),           // 8: actrail.v1.EventEnvelope
	(*SessionMessagesRequest)(nil),  // 9: actrail.v1.SessionMessagesRequest
	(*SessionMessagesResponse)(nil), // 10: actrail.v1.SessionMessagesResponse
}
var file_actrail_v1_transport_proto_depIdxs = []int32{
	0,  // 0: actrail.v1.SendRequest.session:type_name -> actrail.v1.SessionIdentity
	0,  // 1: actrail.v1.EnqueueRequest.session:type_name -> actrail.v1.SessionIdentity
	0,  // 2: actrail.v1.CancelQueueRequest.session:type_name -> actrail.v1.SessionIdentity
	0,  // 3: actrail.v1.InterruptRequest.session:type_name -> actrail.v1.SessionIdentity
	0,  // 4: actrail.v1.RespondUIRequest.session:type_name -> actrail.v1.SessionIdentity
	1,  // 5: actrail.v1.SessionCommandService.Send:input_type -> actrail.v1.SendRequest
	2,  // 6: actrail.v1.SessionCommandService.Enqueue:input_type -> actrail.v1.EnqueueRequest
	3,  // 7: actrail.v1.SessionCommandService.CancelQueue:input_type -> actrail.v1.CancelQueueRequest
	4,  // 8: actrail.v1.SessionCommandService.Interrupt:input_type -> actrail.v1.InterruptRequest
	5,  // 9: actrail.v1.SessionCommandService.RespondUI:input_type -> actrail.v1.RespondUIRequest
	9,  // 10: actrail.v1.SessionCommandService.SessionMessages:input_type -> actrail.v1.SessionMessagesRequest
	7,  // 11: actrail.v1.EventService.Subscribe:input_type -> actrail.v1.SubscribeRequest
	6,  // 12: actrail.v1.SessionCommandService.Send:output_type -> actrail.v1.CommandResponse
	6,  // 13: actrail.v1.SessionCommandService.Enqueue:output_type -> actrail.v1.CommandResponse
	6,  // 14: actrail.v1.SessionCommandService.CancelQueue:output_type -> actrail.v1.CommandResponse
	6,  // 15: actrail.v1.SessionCommandService.Interrupt:output_type -> actrail.v1.CommandResponse
	6,  // 16: actrail.v1.SessionCommandService.RespondUI:output_type -> actrail.v1.CommandResponse
	10, // 17: actrail.v1.SessionCommandService.SessionMessages:output_type -> actrail.v1.SessionMessagesResponse
	8,  // 18: actrail.v1.EventService.Subscribe:output_type -> actrail.v1.EventEnvelope
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_actrail_v1_transport_proto_init() }
func file_actrail_v1_transport_proto_init() {
	if File_actrail_v1_transport_proto != nil {
		return
	}
	file_actrail_v1_transport_proto_msgTypes[9].OneofWrappers = []any{}
	file_actrail_v1_transport_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actrail_v1_transport_proto_rawDesc), len(file_actrail_v1_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_actrail_v1_transport_proto_goTypes,
		DependencyIndexes: file_actrail_v1_transport_proto_depIdxs,
		MessageInfos:      file_actrail_v1_transport_proto_msgTypes,
	}.Build()
	File_actrail_v1_transport_proto = out.File
	file_actrail_v1_transport_proto_goTypes = nil
	file_actrail_v1_transport_proto_depIdxs = nil
}
